name: kiwix
services:
  kiwix:
    build: '.'
    volumes:
    - ~/Documents/zims:/zims
    tty: true
    stdin_open: true
    ports:
        - 8080:8080
    image: benleynen/kiwix:main
    network_mode: host
  