name: build-and-push-main

on:
  push:
    branches: # SOURCE: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#example-using-concurrency-and-the-default-behavior-1
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest # SOURCE: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#choosing-github-hosted-runners
    permissions:
      packages: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v5
    - name: Build image
      run: docker build -f Dockerfile -t ghcr.io/${GITHUB_REPOSITORY}:main .
    - name: Push image
      run: docker push ghcr.io/${GITHUB_REPOSITORY}:main
